---
- name: Add python-pip package (for ansible)
  apt: pkg=python-pip state=present

- name: Add docker-py python module (for ansible)
  pip: name=docker-py state=present

- name: Add docker apt repository key
  apt_key: url=https://get.docker.io/gpg state=present

- name: Add docker apt repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: install docker via apt
  apt: pkg=lxc-docker{{ "-"+docker.version | default("") }} state=present update_cache=yes
